services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: printflow3d-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q 'SELECT 1'"
        ]
      interval: 15s
      timeout: 10s
      retries: 10

  backend:

    build:
      context: ./Backend

    container_name: printflow3d-api

    depends_on:
      sqlserver:
        condition: service_healthy

    environment:

      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}

      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=PrintFlow3D;
        User Id=sa;
        Password=${SA_PASSWORD};
        TrustServerCertificate=True;

    ports:
      - "5000:8080"

    volumes:
      - uploads_data:/app/uploads

  frontend:

    build:
      context: ./Frontend

    container_name: printflow3d-frontend

    depends_on:
      - backend

    ports:
      - "4200:80"

volumes:
  sqlserver_data:
  uploads_data: