services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU18-ubuntu-22.04

    container_name: printflow-sqlserver

    restart: always

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}

    volumes:
      - sqlserver-data:/var/opt/mssql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pidof sqlservr || exit 1"
        ]
      interval: 20s
      timeout: 10s
      retries: 10

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

    networks:
      - printflow

  backend:

    image: ${BACKEND_IMAGE}:${IMAGE_TAG}

    container_name: printflow-api

    restart: always

    depends_on:
      sqlserver:
        condition: service_healthy

    environment:

      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=PrintFlow3D;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True;

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}

      Database__ApplyMigrationsOnStartup: ${APPLY_MIGRATIONS}

    volumes:
      - uploads:/app/uploads

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://localhost:8080/health || exit 1"
        ]
      interval: 20s
      timeout: 5s
      retries: 5

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

    networks:
      - printflow

  frontend:

    image: ${FRONTEND_IMAGE}:${IMAGE_TAG}

    container_name: printflow-frontend

    restart: always

    depends_on:
      backend:
        condition: service_healthy

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

    networks:
      - printflow

volumes:

  sqlserver-data:

  uploads:

networks:

  printflow: