version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: printflow-sqlserver

    restart: always

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sqlserver-data:/var/opt/mssql

    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "${SA_PASSWORD}",
          "-Q",
          "SELECT 1"
        ]

      interval: 20s

      timeout: 10s

      retries: 10

  logging:

    driver: json-file
    options:
      max-size: "20m"
      max-file: "5"

    networks:
      - printflow


  backend:

    image: ${BACKEND_IMAGE}:${IMAGE_TAG}

    container_name: printflow-api

    restart: always

    depends_on:
      sqlserver:
        condition: service_healthy

    environment:

      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=PrintFlow3D;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=true;

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}

    ports:
      - "5000:8080"

    volumes:

      - uploads:/app/uploads
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

    logging:

      driver: json-file

      options:

        max-size: "20m"

        max-file: "5"

    networks:
      - printflow



  frontend:

    image: ${FRONTEND_IMAGE}:${IMAGE_TAG}

    container_name: printflow-frontend

    restart: always

    depends_on:
      backend:
        condition: service_healthy
        
    ports:
      - "4200:80"

    logging:

      driver: json-file

      options:

        max-size: "20m"

        max-file: "5"

    networks:
      - printflow



volumes:

  sqlserver-data:

  uploads:


networks:

  printflow:

    driver: bridge