workflow:
  rules:
    # Merge Request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

    # Feature
    - if: '$CI_COMMIT_BRANCH =~ /^feature\/.*$/'

    # Development
    - if: '$CI_COMMIT_BRANCH == "dev"'

    # Staging
    - if: '$CI_COMMIT_BRANCH == "staging"'

    # Production
    - if: '$CI_COMMIT_BRANCH == "main"'

    # Git Tags (Release)
    - if: '$CI_COMMIT_TAG'